// Cookie Manager Types and Utilities

export type CookieSameSite = 'Strict' | 'Lax' | 'None';

export type Cookie = {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires?: number; // Unix timestamp in seconds, -1 for session cookies
  httpOnly: boolean;
  secure: boolean;
  sameSite: CookieSameSite;
};

export type CookieImportFormat = 'json' | 'netscape';

export type CookieImportOptions = {
  format: CookieImportFormat;
  overwrite: boolean; // If true, replace existing cookies; if false, merge
};

export type CookieExportFormat = 'json' | 'netscape';

// Parse Netscape cookie format (used by curl, wget, etc.)
// Format: domain	flag	path	secure	expiration	name	value
export function parseNetscapeCookies(content: string): Cookie[] {
  const cookies: Cookie[] = [];
  const lines = content.split('\n');
  
  for (const line of lines) {
    const trimmed = line.trim();
    
    // Skip comments and empty lines
    if (!trimmed || trimmed.startsWith('#')) continue;
    
    const parts = trimmed.split('\t');
    if (parts.length < 7) continue;
    
    const [domain, flag, path, secure, expiration, name, value] = parts;
    
    cookies.push({
      name,
      value,
      domain,
      path,
      expires: expiration === '0' ? -1 : parseInt(expiration, 10),
      httpOnly: false, // Netscape format doesn't include httpOnly
      secure: secure.toLowerCase() === 'true',
      sameSite: 'Lax',
    });
  }
  
  return cookies;
}

// Export cookies to Netscape format
export function exportNetscapeCookies(cookies: Cookie[]): string {
  const lines: string[] = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by Cromminm',
    '# Edit at your own risk.',
    '',
  ];
  
  for (const cookie of cookies) {
    const domain = cookie.domain;
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path;
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiration = cookie.expires === -1 ? '0' : String(cookie.expires);
    const name = cookie.name;
    const value = cookie.value;
    
    lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}`);
  }
  
  return lines.join('\n');
}

// Parse JSON cookie format (Playwright/Puppeteer format)
export function parseJsonCookies(content: string): Cookie[] {
  try {
    const parsed = JSON.parse(content);
    
    // Handle array of cookies
    if (Array.isArray(parsed)) {
      return parsed.map(normalizeCookie);
    }
    
    // Handle object with cookies property
    if (parsed.cookies && Array.isArray(parsed.cookies)) {
      return parsed.cookies.map(normalizeCookie);
    }
    
    throw new Error('Invalid JSON cookie format');
  } catch (error) {
    throw new Error(`Failed to parse JSON cookies: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

// Normalize cookie object to our format
function normalizeCookie(cookie: any): Cookie {
  return {
    name: cookie.name || '',
    value: cookie.value || '',
    domain: cookie.domain || '',
    path: cookie.path || '/',
    expires: cookie.expires !== undefined ? cookie.expires : (cookie.expirationDate ? cookie.expirationDate : -1),
    httpOnly: cookie.httpOnly !== undefined ? cookie.httpOnly : false,
    secure: cookie.secure !== undefined ? cookie.secure : false,
    sameSite: cookie.sameSite || 'Lax',
  };
}

// Export cookies to JSON format
export function exportJsonCookies(cookies: Cookie[]): string {
  return JSON.stringify(cookies, null, 2);
}

// Validate cookie
export function validateCookie(cookie: Cookie): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  if (!cookie.name) {
    errors.push('Cookie name is required');
  }
  
  if (!cookie.domain) {
    errors.push('Cookie domain is required');
  }
  
  if (!cookie.path) {
    errors.push('Cookie path is required');
  }
  
  if (cookie.sameSite === 'None' && !cookie.secure) {
    errors.push('SameSite=None requires Secure flag');
  }
  
  return {
    valid: errors.length === 0,
    errors,
  };
}

// Merge cookies (used for import with overwrite=false)
export function mergeCookies(existing: Cookie[], incoming: Cookie[]): Cookie[] {
  const merged = [...existing];
  
  for (const incomingCookie of incoming) {
    const existingIndex = merged.findIndex(
      (c) => c.name === incomingCookie.name && c.domain === incomingCookie.domain && c.path === incomingCookie.path
    );
    
    if (existingIndex >= 0) {
      // Replace existing cookie
      merged[existingIndex] = incomingCookie;
    } else {
      // Add new cookie
      merged.push(incomingCookie);
    }
  }
  
  return merged;
}

// Filter expired cookies
export function filterExpiredCookies(cookies: Cookie[]): Cookie[] {
  const now = Math.floor(Date.now() / 1000);
  return cookies.filter((cookie) => cookie.expires === -1 || cookie.expires > now);
}
